import * as T from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { Firefly } from './firefly';
const scene=new T.Scene();scene.background=new T.Color('#121e29');
const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);camera.position.set(3.4,2.5,4.5);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;document.body.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.85,0);controls.enableDamping=true;controls.minDistance=2.5;controls.maxDistance=10;controls.maxPolarAngle=Math.PI*.48;
scene.add(new T.HemisphereLight('#c7e4ef','#344131',2));const key=new T.DirectionalLight('#fff0c9',3);key.position.set(-3,6,4);key.castShadow=true;scene.add(key);
const ground=new T.Mesh(new T.CircleGeometry(8,80),new T.MeshStandardMaterial({color:'#24363a',roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=.015;ground.receiveShadow=true;scene.add(ground);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.55,.5,1.1));composer.addPass(new OutputPass());
let firefly:Firefly|undefined;
new GLTFLoader().load('./models/firefly-animated.glb',gltf=>{firefly=new Firefly(gltf);scene.add(firefly.object);document.querySelector('#message')!.textContent='Моргает, шевелит усиками и мягко покачивается.';},undefined,()=>{document.querySelector('#message')!.textContent='Не удалось загрузить модель.';});
for(const mode of ['Sit','Fly'] as const)document.querySelector(`#${mode.toLowerCase()}`)!.addEventListener('click',()=>{firefly?.setMode(mode);document.querySelector('#sit')!.setAttribute('aria-pressed',String(mode==='Sit'));document.querySelector('#fly')!.setAttribute('aria-pressed',String(mode==='Fly'));});
document.querySelector<HTMLInputElement>('#glow')!.addEventListener('input',event=>firefly?.setGlowColor((event.target as HTMLInputElement).value));
let previous=performance.now();renderer.setAnimationLoop(time=>{const dt=Math.min(.05,(time-previous)/1000);previous=time;firefly?.update(dt);controls.update();composer.render();});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});
