import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { CharacterController } from '../src/controller';
import { createNpcs } from '../src/npcs';
import { FruitWorld } from '../src/fruits';
import { captureGame, parseSave, restoreGame } from '../src/save-game';
import { KIRBY_VARIANTS, cloneVariant } from '../src/variants';
import { STATION } from '../src/coaster';
test('save round trip restores variant, positions, growth targets, fruit visibility and counters',async()=>{
 const bytes=await readFile(new URL('../public/models/kirby-animated.glb',import.meta.url));
 const model=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
 const variant=KIRBY_VARIANTS[4],player=new CharacterController(cloneVariant(model.scene,variant,false),model.animations);
 const npcs=createNpcs(model.scene,model.animations,variant),world=new FruitWorld();
 player.actor.position.set(12,0,33);player.yaw=.8;player.grow();player.grow();
 player.achievements.add('bench');player.achievements.add('star');player.achievements.add('firefly');npcs[3].achievements.add('balloon');
 player.skyCheckpoint=3;
 player.starBlessed=true;player.starRemaining=18;player.starCooldown=108;
 npcs[3].actor.position.set(-15,0,90);npcs[3].grow();
 world.restore(world.fruits.map((_,i)=>i<3),1);
 const save=parseSave(JSON.stringify(captureGame(player,variant,npcs,world)));
 const restored=new CharacterController(cloneVariant(model.scene,variant,false),model.animations);
 const friends=createNpcs(model.scene,model.animations,variant),fruits=new FruitWorld();
 restoreGame(save,restored,friends,fruits);
 assert.deepEqual([...restored.achievements],['bench','star','firefly']);assert(friends[3].achievements.has('balloon'));
 assert.throws(()=>parseSave(JSON.stringify({...save,player:{...save.player,achievements:['bench','bench']}})));
 assert.equal(restored.skyCheckpoint,3);assert(restored.starBlessed);assert.equal(restored.starRemaining,18);assert.equal(restored.starCooldown,108);
 assert.equal(save.player.variant,variant[0]);assert.equal(restored.actor.position.x,12);assert.equal(restored.actor.position.z,33);
 assert.equal(restored.yaw,.8);assert(Math.abs(restored.actor.scale.x-1.2)<1e-9);assert.equal(restored.fruitsEaten,2);
 assert.equal(friends[3].actor.position.z,90);assert.equal(friends[3].actor.scale.x,1.1);assert.equal(friends[3].fruitsEaten,1);
 assert.equal(fruits.onMap,67);assert.equal(fruits.eatenByNpcs,1);assert(!fruits.fruits[0].object.visible);assert(fruits.fruits[3].object.visible);
 const ride=captureGame(player,variant,npcs,world,true);assert.equal(ride.player.x,STATION.x);assert.equal(ride.player.z,STATION.z-8);
 assert.throws(()=>parseSave(JSON.stringify({...save,fruits:[]})));
 assert.throws(()=>parseSave('broken'));
 const nightSave=parseSave(JSON.stringify(captureGame(player,variant,npcs,world,false,undefined,true)));assert.equal(nightSave.night,true);const timed=parseSave(JSON.stringify({...save,dayPhase:.137}));assert.equal(timed.dayPhase,.137);assert.throws(()=>parseSave(JSON.stringify({...save,dayPhase:1})));assert.throws(()=>parseSave(JSON.stringify({...save,night:'yes'})));
 assert.throws(()=>parseSave(JSON.stringify({...save,mazeStar:'yes'})));
 const oldFormat=JSON.parse(JSON.stringify(save));delete oldFormat.player.achievements;for(const npc of oldFormat.npcs)delete npc.achievements;
 restoreGame(parseSave(JSON.stringify(oldFormat)),restored,friends,fruits);assert.deepEqual([...restored.achievements],['star']);assert.equal(friends[3].achievements.size,0);assert.equal(restored.fruitsEaten,2);
 const legacy={...save};delete legacy.mazeStar;delete legacy.starRemaining;delete legacy.starCooldown;restoreGame(parseSave(JSON.stringify(legacy)),restored,friends,fruits);assert(!restored.starBlessed);assert.equal(restored.starRemaining,0);assert.equal(restored.starCooldown,0);
 assert.throws(()=>parseSave(JSON.stringify({...save,starRemaining:31})));assert.throws(()=>parseSave(JSON.stringify({...save,starCooldown:-1})));
});
