import {test} from 'node:test';
import assert from 'node:assert/strict';
import {allTasks,createStarfall,collectStar,finishStarfall,starfallPhase,PREPARE_MS,COLLECT_MS,CELEBRATE_MS,STAR_INTERVAL,validStarfall} from '../src/starfall';
import {SCORE_ACTIONS,scoreOf} from '../src/score';
const player=()=>({name:'Кирби',variant:0,base:36,fruits:4,size:1.4,bonus:0,collected:[] as number[]});
test('every interactive task is required, including swimming and firefly ride',()=>{assert(allTasks(SCORE_ACTIONS));for(const missing of SCORE_ACTIONS)assert(!allTasks(SCORE_ACTIONS.filter(a=>a!==missing)));});
test('one shared timeline covers countdown, collection, celebration and results',()=>{const s=createStarfall(100,'Кирби');assert.equal(starfallPhase(s,100),'countdown');assert.equal(starfallPhase(s,100+PREPARE_MS),'collect');assert.equal(starfallPhase(s,100+PREPARE_MS+COLLECT_MS),'celebrate');assert.equal(starfallPhase(s,s.endsAt+CELEBRATE_MS),'done');});
test('stars are personal, duplicate safe, time limited, with a strict 30 point cap',()=>{const s=createStarfall(0,'Кирби');s.players.a=player();s.players.b=player();assert(!collectStar(s,'a',0,0));assert(!collectStar(s,'unknown',0,s.startsAt+3000));assert(!collectStar(s,'a',NaN,s.startsAt+3000));assert(collectStar(s,'a',0,s.startsAt+3000));assert(collectStar(s,'b',0,s.startsAt+3000));assert(!collectStar(s,'a',0,s.startsAt+3000));assert(!collectStar(s,'a',4,s.startsAt+3000));for(let i=1;i<60;i++)collectStar(s,'a',i,s.startsAt+i*STAR_INTERVAL+3000);assert.equal(s.players.a.bonus,30);assert.equal(s.players.b.bonus,1);assert(!collectStar(s,'b',59,s.endsAt));assert(validStarfall(s));});
test('results freeze exactly once and bonus does not change fruit count or size',()=>{const s=createStarfall(0,'Кирби');s.players.a=player();s.players.b={...player(),base:40};collectStar(s,'a',4,s.startsAt+4*STAR_INTERVAL+3000);assert.equal(s.players.a.bonus,3);assert(!finishStarfall(s,s.endsAt-1));assert(finishStarfall(s,s.endsAt));assert.equal(s.results?.[0].id,'b');assert.equal(s.results?.[1].points,39);s.players.b.base=0;assert(!finishStarfall(s,s.endsAt+1));assert.equal(s.results?.[0].points,40);assert.equal(scoreOf({fruitsEaten:4,achievements:new Set(SCORE_ACTIONS),bonusPoints:3}),43);assert.equal(s.players.a.fruits,4);assert.equal(s.players.a.size,1.4);});
